query EntityDefinition($name: String!, $bundle: String, $field_types: FieldTypes) {
  definition: entityDefinition(name: $name, bundle: $bundle, field_types: $field_types) {
    label
    fields {
      id
      label
      description
      type
      required
      multiple
      maxNumItems
      status
      defaultValue
      isReference
      isHidden
      weight
      settings
    }
  }
}
